/**
 * buildJson.js
 * Joins aggregated totals + the approved region/country coordinate lookup
 * into the EXACT schema currently consumed by index.html in the
 * Nauticworx/Partner-Program-Mapbox repo (confirmed by inspecting the live
 * data/network-coverage.json and index.html on 2026-09-21):
 *
 *   {
 *     _meta: {...},               // NOT read by index.html, kept for parity/documentation
 *     regions: [
 *       {
 *         id, name, coordinates: [lng, lat],
 *         charterers, brokers, fleetOwners, dualAccounts, uniqueAccounts,
 *         countries: [
 *           { id, name, coordinates: [lng, lat],
 *             charterers, brokers, fleetOwners, dualAccounts, uniqueAccounts }
 *         ]
 *       }
 *     ]
 *   }
 *
 * index.html reads region.id/.name/.coordinates/.uniqueAccounts/.charterers/
 * .brokers/.fleetOwners/.dualAccounts/.countries (defaulting countries to []
 * if absent), and the same fields per country. No other top-level keys are
 * read, but _meta is retained here to match the current file's shape and to
 * document provenance.
 */

const { CANONICAL_REGIONS, REGION_GEO, COUNTRY_GEO } = require("./constants");

/**
 * @param {Object} regionTotals - from aggregate.js
 * @param {Object} countryTotals - from aggregate.js, keyed by country NAME
 * @param {Object} [countryToRegion] - optional map of country name -> canonical
 *   region name, needed only when country-level rows exist. Not used by the
 *   current pilot (zero country rows).
 * @param {Object} [meta] - optional override for the _meta block
 * @returns {Object} JSON object matching the live schema
 */
function buildJson(regionTotals, countryTotals, countryToRegion = {}, meta = {}) {
  const countriesByRegion = {};
  for (const region of CANONICAL_REGIONS) countriesByRegion[region] = [];

  for (const [countryName, totals] of Object.entries(countryTotals)) {
    const region = countryToRegion[countryName];
    if (!region || !countriesByRegion[region]) {
      // A country total exists but has no approved region assignment or
      // coordinate - this is a build-time error, not something to guess at.
      throw new Error(
        `buildJson: country "${countryName}" has aggregated totals but no approved region assignment/coordinates. ` +
        `Add it to countryToRegion and constants.COUNTRY_GEO before building - do not invent coordinates.`
      );
    }
    const geo = COUNTRY_GEO[countryName];
    if (!geo) {
      throw new Error(`buildJson: no approved coordinates for country "${countryName}" in constants.COUNTRY_GEO.`);
    }
    countriesByRegion[region].push({
      id: geo.id,
      name: countryName,
      coordinates: geo.coordinates,
      charterers: totals.charterers,
      brokers: totals.brokers,
      fleetOwners: totals.fleetOwners,
      dualAccounts: totals.dualAccounts,
      uniqueAccounts: totals.uniqueAccounts,
    });
  }

  const regions = CANONICAL_REGIONS.map((regionName) => {
    const geo = REGION_GEO[regionName];
    const totals = regionTotals[regionName] || { charterers: 0, brokers: 0, fleetOwners: 0, dualAccounts: 0, uniqueAccounts: 0 };
    return {
      id: geo.id,
      name: regionName,
      coordinates: geo.coordinates,
      charterers: totals.charterers,
      brokers: totals.brokers,
      fleetOwners: totals.fleetOwners,
      dualAccounts: totals.dualAccounts,
      uniqueAccounts: totals.uniqueAccounts,
      countries: countriesByRegion[regionName],
    };
  });

  return {
    _meta: {
      description: "Nauticworx Partner Program Mapbox - network-coverage output generated by network-coverage/ pipeline.",
      headlineField: "uniqueAccounts",
      note: "uniqueAccounts is authoritative and must NOT be derived by summing charterers + brokers + fleetOwners, because dualAccounts overlap other account types.",
      accountFields: ["charterers", "brokers", "fleetOwners", "dualAccounts", "uniqueAccounts"],
      taxonomySource: "Canonical 16-region Nauticworx Partner Program taxonomy",
      ...meta,
    },
    regions,
  };
}

module.exports = { buildJson };
